[build]
base = "."
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "18"
REACT_APP_API_URL = "https://interim-backend-production.up.railway.app"

# Handle API calls - proxy to Railway backend (this must come FIRST)
[[redirects]]
from = "/api/*"
to = "https://interim-backend-production.up.railway.app/api/:splat"
status = 200
force = true

# Handle client-side routing - this should be LAST
[[redirects]]
from = "/*"
to = "/index.html"
status = 200